### ISSUE TITLE
MapSources not making sure CSV files contain valid records

### ISSUE THREAD

**Issue by wb8tyw** [ham-radio-software/D-Rats#119]
Original Title: MapSourcePointError: not enough values to unpack (expected 7, got 1)

testing latest code I am now getting a continous stream of these errors:

during handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:/msys64\home\mauri\d-rats-dev\D-Rats-python3_tyw/d_rats/map_sources.py", line 588, in init
point = self.__parse_line(line)
File "C:/msys64\home\mauri\d-rats-dev\D-Rats-python3_tyw/d_rats/map_sources.py", line 646, in __parse_line
raise MapSourcePointError(str(err))
d_rats.map_sources.MapSourcePointError: not enough values to unpack (expected 7, got 1)
02/16/2022 17:15:18:INFO:MapFileSource:parse_line broad-execpt
Traceback (most recent call last):
File "C:/msys64\home\mauri\d-rats-dev\D-Rats-python3_tyw/d_rats/map_sources.py", line 642, in __parse_line
ident, icon, lat, lon, alt, comment, show = line.split(",", 6)
ValueError: not enough values to unpack (expected 7, got 1)
02/16/2022 17:15:18:INFO:MapFileSource:Failed to parse
Traceback (most recent call last):
File "C:/msys64\home\mauri\d-rats-dev\D-Rats-python3_tyw/d_rats/map_sources.py", line 642, in __parse_line
ident, icon, lat, lon, alt, comment, show = line.split(",", 6)
ValueError: not enough values to unpack (expected 7, got 1)

**Comment by wb8tyw** [comment]
Any place that is reporting a broad-except or similar message is where I have added diagnostics to try to determine what the actual exception handling should be.

This is because broad-exceptions tend to hide bugs in the code.

To diagnose this, we really need to know what the line that split() is called on looks like.

Since it is not printed out, then adding a print statement with some text to indicates what it is can be locally added. Or a logger.debug() statement, which may be a good idea until the broad-exception is fixed to proper exception handling.

In this case it would be helpful to know the group, as that will tell which file below to look in for the bad data.

I am suspecting that there is an invalid line in one of the files in ~/.d-rats-ev/static-locations.

If that is the case, we need to figure out how did the invalid data get into the file.

Do you remember adding a point to the map before this happened?

Another possibility is a malformed message for a station location was received and a bug allowed that bad data into the file. So we need may need to look at that code.

**Comment by wb8tyw** [comment]
[maurizioandreotti](https://github.com/maurizioandreotti) commented [on Feb 17]
Yes, you are right, I recall I had a static point added by the former
version of drats run in the same pc and then opened the new version.

The errors went away after I removed the point.

If add  a point with the new drats, there are no errors in the log.

**Comment by wb8tyw** [comment]
Future changes to map_sources:

1. Change the second except line MapFileSource.init to except MapSourcePointError, and remove the redundant log message.
2. Change the except line in MapFileSource.__parse_line to be except ValueError:

**Comment by wb8tyw** [comment]
Before this bug can be fully resolved, we need to verify that the parts of d-rats that add entries to the map source CSV files can not create an invalid entry and that in the event that they do, the map source editor can fix the entry.

**Comment by wb8tyw** [comment]
CSV files need to be read and written by an API for writing CSV files.
We probably want to look at a more robust format for storing the data.
With the current d-rats code, both old and new, invalid user input to a dialog box or possibly station information of a remote station can corrupt the data.
