### ISSUE TITLE
MacOs - Config - Ratflector edit

### ISSUE THREAD

**Issue by maurizioandreotti** [ham-radio-software/D-Rats#184]
At first run I had edited the original ratflector substituting it with k3pdr.
now if I try edit it I get the error pop-up window stating:

```

Traceback (most recent call last):

  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-wb8tyw_bugfix146/d_rats/config.py", line 1652, in but_mod
    name, port, info = prompt_for_port(values[2], values[3], values[6])
                                       ~~~~~~^^^

TypeError: 'NoneType' object is not subscriptable

```

in console I see:

```
15:56:INFO:D-Rats:---- GUI Exception ----
%s
---- End ----
Stack (most recent call last):
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-wb8tyw_bugfix146/./d-rats.py", line 240, in <module>
    main()
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-wb8tyw_bugfix146/./d-rats.py", line 234, in main
    app.main()
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-wb8tyw_bugfix146/d_rats/mainapp.py", line 2124, in main
    self.run(None)
  File "/Users/maurizio/Virtualenvs/d-rats4/lib/python3.11/site-packages/gi/overrides/Gio.py", line 42, in run
    return Gio.Application.run(self, *args, **kwargs)
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-wb8tyw_bugfix146/d_rats/mainwindow.py", line 244, in _activate_prefs
    saved = self._config.show(parent=self._window)
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-wb8tyw_bugfix146/d_rats/config.py", line 2699, in show
    result = drats_ui.run()
  File "/Users/maurizio/Virtualenvs/d-rats4/lib/python3.11/site-packages/gi/overrides/Gtk.py", line 585, in run
    return Gtk.Dialog.run(self, *args, **kwargs)
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-wb8tyw_bugfix146/./d-rats.py", line 93, in handle_exception
    MODULE_LOGGER.info("---- GUI Exception ----\n%s\n---- End ----\n",


```

**Comment by maurizioandreotti** [comment]
I tried recreting the situation, but now it all works,...

I deleted all RATFlectors, Drats at repopen recreadted the standard one.

I added the K3pdr, one and enabled instead of the def one and worked,... then edited saved several times, and seems working.

for time being let's park this issues. if will come back I will try to understand better the context.
