### ISSUE TITLE
Repeater | macos | edit users

### ISSUE THREAD

**Issue by maurizioandreotti** [ham-radio-software/D-Rats#203]
PRESSING "EDIT USERS" button in Repeater GUI results into this:

`

Traceback (most recent call last):
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/./d-rats_repeater.py", line 950, in clicked_edit_users
    self.platform.open_text_file(self.platform.config_file("users.txt"))
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/d_rats/dplatform_macos.py", line 151, in open_text_file
    MacOSXPlatform._unix_doublefork_run(macos_textedit, path)
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-gh/d_rats/dplatform_macos.py", line 116, in _unix_doublefork_run
    os.execlp(args[0], *args)
  File "<frozen os>", line 557, in execlp
  File "<frozen os>", line 574, in execvp
  File "<frozen os>", line 597, in _execvpe
FileNotFoundError: [Errno 2] No such file or directory
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.
The process has forked and you cannot use this CoreFoundation functionality safely. You MUST exec().
Break on __THE_PROCESS_HAS_FORKED_AND_YOU_CANNOT_USE_THIS_COREFOUNDATION_FUNCTIONALITY___YOU_MUST_EXEC__() to debug.

`

**Comment by wb8tyw** [comment]
Process Has Forked is related to [Mac OS GIO application Issues](https://github.com/ham-radio-software/D-Rats/issues/196)

Need to determine the cause of the FileNotFoundError: [Errno 2] No such file or directory message.

On Mac OS, the open text edit tries to open the program named ""/Applications/TextEdit.app/Contents/MacOS/TextEdit"
