### ISSUE TITLE
spell.py - line 89 rror --> aspell missing

### ISSUE THREAD

**Issue by maurizioandreotti** [ham-radio-software/D-Rats#210]
In the console while saving settings->messages , getting this error:
```

06/21/2023 22:49:58:DEBUG:Spelling:Did not find aspell program
Traceback (most recent call last):
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats/d_rats/spell.py", line 137, in test
    spell = self.lookup_word("speling")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats/d_rats/spell.py", line 89, in lookup_word
    raise SpellNoSpellCheckerError("Program %s present" % self.__aspell)
d_rats.spell.SpellNoSpellCheckerError: Program aspell present

```

ths gets fixed installing aspell, e.g.:
- MacOs: brew install aspell
-

**Comment by maurizioandreotti** [comment]
need to verify aspell  to be present in the list of  requirements (optional)
