### ISSUE TITLE
Form save/send/print has errors

### ISSUE THREAD

**Issue by wb8tyw** [ham-radio-software/D-Rats#215]
> 6. Attempting to save, send, or print an ARRL radiogram, an NHC
> Hurricane Report, a Skywarn Report or the hics260 form causes an
> error, but calls to print the ICS forms are rendered correctly and
> can be saved, sent, or printed in Firefox.  Trying to fill out the
> above forms and the program will not allow the message to be saved or
> sent.  It always gives an error message that can be ignored.  The
> forms are presently unusable.

**Comment by wb8tyw** [comment]
Need to know the specific error messages produced.

**Comment by wb8tyw** [comment]
Reproduced with radiogram
```text
Traceback (most recent call last):
  File "/mnt/aviary/home/malmberg/work/d-rats/D-Rats/d_rats/ui/message_list.py", line 271, in form_done
dlg.save_to(filename)
  File "/mnt/aviary/home/malmberg/work/d-rats/D-Rats/d_rats/formgui.py", line 1508, in 
save_to
field.update_node()
  File "/mnt/aviary/home/malmberg/work/d-rats/D-Rats/d_rats/formgui.py", line 1058, in update_node
    self.entry.update_node()
  File "/mnt/aviary/home/malmberg/work/d-rats/D-Rats/d_rats/formgui.py", line 759, in update_node
    child.unsetProp("set")
AttributeError: 'lxml.etree._Element' object has no attribute 'unsetProp'
```

**Comment by wb8tyw** [comment]
Two sections of code found that had not been converted to lxml calls.
