### ISSUE TITLE
New email - attachment - remove attachment

### ISSUE THREAD

**Issue by maurizioandreotti** [ham-radio-software/D-Rats#226]
situation: creating a new email added a txt file as attachment
issue: clicking on remove attachment I get:

`07/10/2023 13:07:09:INFO:KeyedListWidget:get_selected: Nothing was selected
07/10/2023 13:07:17:INFO:Utils.run_or_error:broad-exception
Traceback (most recent call last):
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-version/d_rats/utils.py", line 251, in runner
    function(*args, **kwargs)
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-version/d_rats/formgui.py", line 1736, in button_remove
    self.del_attachment(name)
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-version/d_rats/formgui.py", line 1433, in del_attachment
    els[0].unlinkNode()
    ^^^^^^^^^^^^^^^^^
AttributeError: 'lxml.etree._Element' object has no attribute 'unlinkNode'
07/10/2023 13:07:17:INFO:Utils.log_exception:-- Exception: --
Traceback (most recent call last):
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-version/d_rats/utils.py", line 251, in runner
    function(*args, **kwargs)
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-version/d_rats/formgui.py", line 1736, in button_remove
    self.del_attachment(name)
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-version/d_rats/formgui.py", line 1433, in del_attachment
    els[0].unlinkNode()
    ^^^^^^^^^^^^^^^^^
AttributeError: 'lxml.etree._Element' object has no attribute 'unlinkNode'
Traceback (most recent call last):
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-version/d_rats/utils.py", line 251, in runner
    function(*args, **kwargs)
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-version/d_rats/formgui.py", line 1736, in button_remove
    self.del_attachment(name)
  File "/Users/maurizio/Virtualenvs/d-rats4/D-Rats-version/d_rats/formgui.py", line 1433, in del_attachment
    els[0].unlinkNode()
    ^^^^^^^^^^^^^^^^^
AttributeError: 'lxml.etree._Element' object has no attribute 'unlinkNode'
07/10/2023 13:07:17:INFO:Utils.log_exception:----------------

`

**Comment by wb8tyw** [comment]
In testing this, I see that the attachment menu has three buttons. "Add" which appears to add the attachment, and "Remove" which is supposed to remove the attachment, and is current broken, and "Save", which does not seem to do anything but log "Nothing was selected."
