### ISSUE TITLE
D-Rats Repeater accept new GPS crash with TypeError

### ISSUE THREAD

**Issue by wb8tyw** [ham-radio-software/D-Rats#251]
Crash reported in D-Rats Repeater:
```text
./d-rats_repeater.py
Exception in thread Thread-2 (_repeat):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/riggs498/D-Rats/./d-rats_repeater.py", line 419, in _repeat
    self.accept_new_gps()
  File "/home/riggs498/D-Rats/./d-rats_repeater.py", line 391, in
accept_new_gps
    addr_str = "%s:$i" % addr
TypeError: not all arguments converted during string formatting
```

**Comment by wb8tyw** [comment]
Not sure how long this code has been broken, but this does not look like something that was changed for the pythoni3 version.
```python
        addr_str = "%s:%i" % (addr, csocket)
        self.logger.info("accept_new: Accepted new client %s", addr_str)
```
